apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-sentinel
spec:
  replicas: {{ .Values.replicas.sentinel }}
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
{{ include "labels.standard" . | indent 8 }}
    spec:
      containers:
      - name: sentinel
        image: {{ .Values.redis_image }}
        resources:
{{ toYaml .Values.resources.sentinel | indent 10 }}
        env:
          - name: SENTINEL
            value: "true"
{{ include "redisEnv.common" . | indent 10 }}
        ports:
          - containerPort: 26379
        {{- if .Values.redisConfig.overrideDefaults }}
        volumeMounts:
{{ include "redisConfigVolumeMount" . | indent 10 }}
        {{- end -}}
        {{- if .Values.probes.enabled }}
        livenessProbe:
{{ toYaml .Values.probes.sentinel.liveness | indent 10 }}
        readinessProbe:
{{ toYaml .Values.probes.sentinel.readiness | indent 10 }}
        {{- end }}
      {{- if .Values.redisConfig.overrideDefaults }}
      volumes:
{{ include "redisConfigVolume" . | indent 8 }}
      {{- end -}}
